spring:
  application:
    name: invex
  server:
    shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: local

  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
---
spring:
  config:
    activate:
      on-profile: dev

  r2dbc:
    url: r2dbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool.enabled: true

server:
  port: ${PORT:1000}