spring:
  application:
    name: invex
  server:
    shutdown: graceful
---
spring:
  profiles:
    active: local

  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
---
spring:
  profiles:
    active: dev

  r2dbc:
    url: r2dbc:postgresql://${database.host}:${database.port}/postgres
    username: ${database.username}
    password: ${database.password}
    pool.enabled: true

server:
  port: ${PORT:1000}