spring:
  application:
    name: invex
  server:
    shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: local

  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
---
spring:
  config:
    activate:
      on-profile: dev

  r2dbc:
    url: r2dbc:mysql://localhost:3306/invex
    username: invex
    password: invex123
    pool.enabled: true

server:
  port: ${PORT:1000}